import { Controller, Get, Query, Res, BadRequestException } from '@nestjs/common';
import type { Response } from 'express';
import { TodosService } from './todos.service';
import { AuthService } from '../auth/auth.service';
import { PlannerService, type PlanDay } from '../attempts/planner.service';

// 每一類訂閱 = 一個獨立日曆，各自在使用者的日曆 App 得到一種顏色。
// 事件層級的顏色 Google/Apple 都不吃，所以「不同顏色」靠拆多條 feed 達成。
type CalendarCategory = 'all' | 'plan' | 'todos';

const CALENDAR_META: Record<CalendarCategory, { name: string; color: string }> = {
  all: { name: 'PassBar 學習計劃', color: '#C8A24B' },
  plan: { name: '📘 PassBar 備考計劃', color: '#3B82F6' },
  todos: { name: '📝 PassBar 待辦事項', color: '#F59E0B' },
};

@Controller('calendar')
export class CalendarController {
  constructor(
    private readonly todosService: TodosService,
    private readonly authService: AuthService,
    private readonly plannerService: PlannerService,
  ) {}

  @Get('feed')
  async getFeed(
    @Query('token') token: string,
    @Query('cat') cat: string,
    @Res() res: Response,
  ) {
    if (!token) {
      throw new BadRequestException('Missing token');
    }

    // cat 決定這條訂閱是哪一個彩色日曆：
    //   plan  → 到考試日的投影排程（複習/練習，即時算，隨做題動態調整）
    //   todos → 使用者手動代辦（autoGenerated=false）
    //   其他  → 全部（投影 + 手動代辦，維持舊訂閱相容）
    const category: CalendarCategory =
      cat === 'plan' ? 'plan' : cat === 'todos' ? 'todos' : 'all';

    const userId = this.authService.verifyCalendarToken(token);
    if (!userId) {
      return this.sendIcs(res, this.emptyIcs(category));
    }

    const dtstamp = this.formatDateIcs(new Date());
    let body = '';

    if (category === 'plan' || category === 'all') {
      const plan = await this.plannerService.projectSchedule(userId);
      body += this.projectionEvents(plan, dtstamp);
    }
    if (category === 'todos' || category === 'all') {
      const todos = (await this.todosService.list(userId)).filter(
        (t) => !t.autoGenerated,
      );
      body += this.todoEvents(todos, dtstamp);
    }

    return this.sendIcs(res, this.wrapCalendar(category, body));
  }

  private sendIcs(res: Response, ics: string) {
    res.setHeader('Content-Type', 'text/calendar; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="passbar-plan.ics"');
    res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
    res.status(200).send(ics);
  }

  private formatDateIcs(date: Date) {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  }

  private formatDateIcsDateOnly(date: Date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    return `${y}${m}${d}`;
  }

  private escapeIcsText(text: string) {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/;/g, '\\;')
      .replace(/,/g, '\\,')
      .replace(/\n/g, '\\n');
  }

  private emptyIcs(category: CalendarCategory) {
    const meta = CALENDAR_META[category];
    return (
      'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//PassBar//Study Plan//EN\r\n' +
      `X-WR-CALNAME:${meta.name}\r\nX-APPLE-CALENDAR-COLOR:${meta.color}\r\n` +
      'END:VCALENDAR\r\n'
    );
  }


  /** VCALENDAR 外殼（header + 事件內文 + footer）。 */
  private wrapCalendar(category: CalendarCategory, body: string) {
    const meta = CALENDAR_META[category];
    return (
      `BEGIN:VCALENDAR\r\n` +
      `VERSION:2.0\r\n` +
      `PRODID:-//PassBar//Study Plan//EN\r\n` +
      `CALSCALE:GREGORIAN\r\n` +
      `METHOD:PUBLISH\r\n` +
      `X-WR-CALNAME:${meta.name}\r\n` +
      `X-APPLE-CALENDAR-COLOR:${meta.color}\r\n` +
      `X-WR-TIMEZONE:UTC\r\n` +
      body +
      `END:VCALENDAR\r\n`
    );
  }

  private allDayEvent(opts: {
    uid: string;
    date: string; // YYYY-MM-DD
    dtstamp: string;
    summary: string;
    description: string;
  }) {
    const start = new Date(`${opts.date}T00:00:00`);
    const end = new Date(start);
    end.setDate(end.getDate() + 1);
    return (
      `BEGIN:VEVENT\r\n` +
      `UID:${opts.uid}\r\n` +
      `DTSTAMP:${opts.dtstamp}\r\n` +
      `DTSTART;VALUE=DATE:${this.formatDateIcsDateOnly(start)}\r\n` +
      `DTEND;VALUE=DATE:${this.formatDateIcsDateOnly(end)}\r\n` +
      `SUMMARY:${this.escapeIcsText(opts.summary)}\r\n` +
      `DESCRIPTION:${this.escapeIcsText(opts.description)}\r\n` +
      `END:VEVENT\r\n`
    );
  }

  /**
   * 投影排程 → VEVENT。UID 用 chapterId:type:occurrence（不含日期），所以重投影把某項
   * 挪到別天時，日曆是「移動同一個事件」而非新增＋留孤兒，達成動態調整。
   */
  private projectionEvents(planDays: PlanDay[], dtstamp: string) {
    let body = '';
    for (const day of planDays) {
      for (const e of day.entries) {
        const emoji = e.type === 'review' ? '📘' : '✍️';
        const kind = e.type === 'review' ? '複習' : '練習';
        body += this.allDayEvent({
          uid: `plan-${e.chapterId}-${e.type}-${e.occurrence}@passbar.app`,
          date: day.date,
          dtstamp,
          summary: `${emoji} ${e.subject} · ${e.chapterName}`,
          description:
            `${kind}${e.type === 'review' ? ` · 第 ${e.occurrence + 1} 輪` : ''}\\n` +
            `Link: https://passbar.app/create?chapters=${encodeURIComponent(e.chapterId)}`,
        });
      }
    }
    return body;
  }

  /** 手動代辦 → VEVENT（僅含有到期日者）。 */
  private todoEvents(todos: any[], dtstamp: string) {
    let body = '';
    for (const todo of todos) {
      if (!todo.dueDate) continue;
      const prefix = todo.status === 'completed' ? '✅ ' : '📝 ';
      let description = `Status: ${todo.status}`;
      if (todo.chapterIds) {
        description += `\\nLink: https://passbar.app/create?chapters=${encodeURIComponent(
          todo.chapterIds,
        )}`;
      }
      body += this.allDayEvent({
        uid: `todo-${todo.id}@passbar.app`,
        date: String(todo.dueDate).slice(0, 10),
        dtstamp,
        summary: prefix + todo.title,
        description,
      });
    }
    return body;
  }
}
