import { Controller, Get, Query, Res, BadRequestException } from '@nestjs/common';
import type { Response } from 'express';
import { TodosService } from './todos.service';
import { AuthService } from '../auth/auth.service';

// 每一類訂閱 = 一個獨立日曆，各自在使用者的日曆 App 得到一種顏色。
// 事件層級的顏色 Google/Apple 都不吃，所以「不同顏色」靠拆多條 feed 達成。
type CalendarCategory = 'all' | 'plan' | 'todos';

const CALENDAR_META: Record<CalendarCategory, { name: string; color: string }> = {
  all: { name: 'PassBar 學習計劃', color: '#C8A24B' },
  plan: { name: '📘 PassBar 備考計劃', color: '#3B82F6' },
  todos: { name: '📝 PassBar 待辦事項', color: '#F59E0B' },
};

@Controller('calendar')
export class CalendarController {
  constructor(
    private readonly todosService: TodosService,
    private readonly authService: AuthService,
  ) {}

  @Get('feed')
  async getFeed(
    @Query('token') token: string,
    @Query('cat') cat: string,
    @Res() res: Response,
  ) {
    if (!token) {
      throw new BadRequestException('Missing token');
    }

    // cat 決定這條訂閱是哪一個彩色日曆：
    //   plan  → 系統產的备考计划（复习/练习，autoGenerated=true）
    //   todos → 使用者手動代辦（autoGenerated=false）
    //   其他  → 全部（維持舊訂閱相容）
    const category: CalendarCategory =
      cat === 'plan' ? 'plan' : cat === 'todos' ? 'todos' : 'all';

    const userId = this.authService.verifyCalendarToken(token);
    if (!userId) {
      return this.sendIcs(res, this.emptyIcs(category));
    }

    const all = await this.todosService.list(userId);
    const todos =
      category === 'plan'
        ? all.filter((t) => t.autoGenerated)
        : category === 'todos'
          ? all.filter((t) => !t.autoGenerated)
          : all;

    const ics = this.generateIcs(todos, category);
    return this.sendIcs(res, ics);
  }

  private sendIcs(res: Response, ics: string) {
    res.setHeader('Content-Type', 'text/calendar; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="passbar-plan.ics"');
    res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
    res.status(200).send(ics);
  }

  private formatDateIcs(date: Date) {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  }

  private formatDateIcsDateOnly(date: Date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    return `${y}${m}${d}`;
  }

  private escapeIcsText(text: string) {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/;/g, '\\;')
      .replace(/,/g, '\\,')
      .replace(/\n/g, '\\n');
  }

  private emptyIcs(category: CalendarCategory) {
    const meta = CALENDAR_META[category];
    return (
      'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//PassBar//Study Plan//EN\r\n' +
      `X-WR-CALNAME:${meta.name}\r\nX-APPLE-CALENDAR-COLOR:${meta.color}\r\n` +
      'END:VCALENDAR\r\n'
    );
  }

  /** 事件標題前綴：完成 ✅，否則依 type 給 emoji（跨平台辨識，不依賴顏色）。 */
  private eventPrefix(todo: { status: string; type: string }) {
    if (todo.status === 'completed') return '✅ ';
    if (todo.type === 'review') return '📘 ';
    if (todo.type === 'practice') return '✍️ ';
    return '📝 ';
  }

  private generateIcs(todos: any[], category: CalendarCategory = 'all') {
    const now = new Date();
    const dtstamp = this.formatDateIcs(now);
    const meta = CALENDAR_META[category];

    let ics = `BEGIN:VCALENDAR\r\n`;
    ics += `VERSION:2.0\r\n`;
    ics += `PRODID:-//PassBar//Study Plan//EN\r\n`;
    ics += `CALSCALE:GREGORIAN\r\n`;
    ics += `METHOD:PUBLISH\r\n`;
    ics += `X-WR-CALNAME:${meta.name}\r\n`;
    ics += `X-APPLE-CALENDAR-COLOR:${meta.color}\r\n`;
    ics += `X-WR-TIMEZONE:UTC\r\n`;

    for (const todo of todos) {
      if (!todo.dueDate) continue;

      const dueDate = new Date(todo.dueDate);
      const dtstart = this.formatDateIcsDateOnly(dueDate);

      const endDate = new Date(dueDate);
      endDate.setDate(endDate.getDate() + 1);
      const dtend = this.formatDateIcsDateOnly(endDate);

      ics += `BEGIN:VEVENT\r\n`;
      ics += `UID:${todo.id}@passbar.app\r\n`;
      ics += `DTSTAMP:${dtstamp}\r\n`;
      ics += `DTSTART;VALUE=DATE:${dtstart}\r\n`;
      ics += `DTEND;VALUE=DATE:${dtend}\r\n`;

      const prefix = this.eventPrefix(todo);
      ics += `SUMMARY:${this.escapeIcsText(prefix + todo.title)}\r\n`;

      let description = `Type: ${todo.type}\\nStatus: ${todo.status}`;
      if (todo.chapterIds) {
        description += `\\n\\nLink: https://passbar.app/create?chapters=${encodeURIComponent(
          todo.chapterIds,
        )}`;
      }
      ics += `DESCRIPTION:${this.escapeIcsText(description)}\r\n`;

      ics += `END:VEVENT\r\n`;
    }

    ics += `END:VCALENDAR\r\n`;
    return ics;
  }
}
