import { Inject, Injectable } from '@nestjs/common';
import { and, desc, eq, inArray } from 'drizzle-orm';
import { DB, type Database } from '../db/db.provider';
import { todos } from '../db/schema';
import {
  PlannerService,
  type ChapterReviewInfo,
  type TodayMissionChapter,
} from '../attempts/planner.service';

type TodoStatus = 'new' | 'scheduled' | 'in_progress' | 'completed';
type TodoType = 'manual' | 'review' | 'practice';

function todayEndIso() {
  const d = new Date();
  d.setHours(23, 59, 59, 999);
  return d;
}

@Injectable()
export class TodosService {
  constructor(
    @Inject(DB) private readonly db: Database,
    private readonly plannerService: PlannerService,
  ) {}

  async list(userId: string) {
    return this.db
      .select()
      .from(todos)
      .where(eq(todos.userId, userId))
      .orderBy(desc(todos.createdAt));
  }

  async create(
    userId: string,
    input: {
      title: string;
      status?: TodoStatus;
      type?: TodoType;
      dueDate?: string | null;
      chapterId?: string | null;
      chapterIds?: string | null;
      autoGenerated?: boolean;
    },
  ) {
    const [created] = await this.db
      .insert(todos)
      .values({
        userId,
        title: input.title,
        status: input.status ?? 'new',
        type: input.type ?? 'manual',
        dueDate: input.dueDate ?? null,
        chapterId: input.chapterId ?? null,
        chapterIds: input.chapterIds ?? null,
        autoGenerated: input.autoGenerated ?? false,
      })
      .returning();
    return created;
  }

  async update(
    userId: string,
    id: string,
    patch: Partial<{
      title: string;
      status: TodoStatus;
      type: TodoType;
      dueDate: string | null;
      chapterId: string | null;
      chapterIds: string | null;
    }>,
  ) {
    const [updated] = await this.db
      .update(todos)
      .set({ ...patch, updatedAt: new Date() })
      .where(and(eq(todos.id, id), eq(todos.userId, userId)))
      .returning({ id: todos.id });
    return Boolean(updated);
  }

  async delete(userId: string, id: string) {
    const [deleted] = await this.db
      .delete(todos)
      .where(and(eq(todos.id, id), eq(todos.userId, userId)))
      .returning({ id: todos.id });
    return Boolean(deleted);
  }

  async syncAutoTodos(userId: string) {
    const { newChapters, reviewChapters } =
      await this.plannerService.fetchTodayMissionForUser(userId);
    return this.syncAutoTodosFromMission(userId, newChapters, reviewChapters);
  }

  private async syncAutoTodosFromMission(
    userId: string,
    newChapters: TodayMissionChapter[],
    reviewChapters: ChapterReviewInfo[],
  ) {
    const allRows = await this.db
      .select()
      .from(todos)
      .where(eq(todos.userId, userId));
    const autoRows = allRows.filter((r) => r.autoGenerated);
    const manualRows = allRows.filter((r) => !r.autoGenerated);

    const allReviewChapterIds = reviewChapters
      .map((c) => c.chapterId)
      .join(',');

    const deletable = autoRows.filter(
      (r) => r.status === 'new' || r.status === 'scheduled',
    );
    if (deletable.length > 0) {
      await this.db.delete(todos).where(
        inArray(
          todos.id,
          deletable.map((r) => r.id),
        ),
      );
    }

    const preservedChapterIds = new Set([
      ...manualRows
        .filter((r) => r.chapterId)
        .map((r) => r.chapterId as string),
      ...autoRows
        .filter(
          (r) =>
            r.chapterId &&
            (r.status === 'in_progress' || r.status === 'completed'),
        )
        .map((r) => r.chapterId as string),
    ]);

    const toInsert: Array<typeof todos.$inferInsert> = [];

    for (const ch of newChapters) {
      if (!preservedChapterIds.has(ch.id)) {
        toInsert.push({
          userId,
          title: `${ch.subject} · ${ch.name}`,
          status: 'new',
          type: 'practice',
          chapterId: ch.id,
          chapterIds: ch.id,
          autoGenerated: true,
          dueDate: todayEndIso().toISOString().slice(0, 10),
        });
      }
    }

    for (const ch of reviewChapters) {
      if (!preservedChapterIds.has(ch.chapterId)) {
        toInsert.push({
          userId,
          title: `${ch.subject} · ${ch.chapterName}`,
          status: 'new',
          type: 'review',
          chapterId: ch.chapterId,
          chapterIds: allReviewChapterIds,
          autoGenerated: true,
          dueDate: todayEndIso().toISOString().slice(0, 10),
        });
      }
    }

    if (toInsert.length > 0) {
      await this.db.insert(todos).values(toInsert);
    }

    return this.list(userId);
  }

  async addChapterAsTodo(
    userId: string,
    chapter: {
      id: string;
      name: string;
      subject: string;
      type: 'practice' | 'review';
      chapterIds?: string;
    },
  ) {
    const existing = await this.db
      .select({ id: todos.id })
      .from(todos)
      .where(and(eq(todos.userId, userId), eq(todos.chapterId, chapter.id)))
      .limit(1);

    if (existing.length > 0) return null;

    const [created] = await this.db
      .insert(todos)
      .values({
        userId,
        title: `${chapter.subject} · ${chapter.name}`,
        status: 'new',
        type: chapter.type,
        chapterId: chapter.id,
        chapterIds: chapter.chapterIds ?? chapter.id,
        autoGenerated: false,
        dueDate: todayEndIso().toISOString().slice(0, 10),
      })
      .returning();

    return created;
  }
}
