import { IsBoolean, IsIn, IsOptional, IsString } from 'class-validator';

export class CreateTodoDto {
  @IsString()
  title!: string;

  @IsOptional()
  @IsIn(['new', 'scheduled', 'in_progress', 'completed'])
  status?: 'new' | 'scheduled' | 'in_progress' | 'completed';

  @IsOptional()
  @IsIn(['manual', 'review', 'practice'])
  type?: 'manual' | 'review' | 'practice';

  @IsOptional()
  @IsString()
  dueDate?: string | null;

  @IsOptional()
  @IsString()
  chapterId?: string | null;

  @IsOptional()
  @IsString()
  chapterIds?: string | null;

  @IsOptional()
  @IsString()
  note?: string | null;

  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean;
}

export class UpdateTodoDto {
  @IsOptional()
  @IsString()
  title?: string;

  @IsOptional()
  @IsIn(['new', 'scheduled', 'in_progress', 'completed'])
  status?: 'new' | 'scheduled' | 'in_progress' | 'completed';

  @IsOptional()
  @IsIn(['manual', 'review', 'practice'])
  type?: 'manual' | 'review' | 'practice';

  @IsOptional()
  @IsString()
  dueDate?: string | null;

  @IsOptional()
  @IsString()
  chapterId?: string | null;

  @IsOptional()
  @IsString()
  chapterIds?: string | null;

  @IsOptional()
  @IsString()
  note?: string | null;
}

export class AddChapterAsTodoDto {
  @IsString()
  id!: string;

  @IsString()
  name!: string;

  @IsString()
  subject!: string;

  @IsIn(['practice', 'review'])
  type!: 'practice' | 'review';

  @IsOptional()
  @IsString()
  chapterIds?: string;
}
