import type { InterfaceLanguage } from './study-settings';

const traditionalLabels: Record<string, string> = {
  'Civil Procedure': '民事訴訟法',
  'Constitutional Law': '憲法',
  'Contracts': '契約法',
  'Criminal Law and Procedure': '刑法與刑事訴訟法',
  'Criminal Law & Procedure': '刑法與刑事訴訟法',
  'Evidence': '證據法',
  'Real Property': '不動產法',
  'Torts': '侵權行為法',
  'Appealability and Review': '上訴可能性與審查',
  'Jurisdiction and Venue': '管轄權與審判地',
  'Jury Trials': '陪審團審判',
  'Law Applied by Federal Courts': '聯邦法院適用之法律',
  'Motions': '動議',
  'Pretrial Procedures': '審前程序',
  'Verdicts and Judgments': '裁決與判決',
  'Federal-State Relations': '聯邦與州關係',
  'Individual Rights': '個人權利',
  'Judicial Review': '司法審查',
  'Separation of Powers': '權力分立',
  'Contract Content and Meaning': '契約內容與解釋',
  'Defenses to enforceability': '可執行性抗辯',
  'Formation of Contracts': '契約成立',
  'Performance, Breach, and Discharge': '履行、違約與義務消滅',
  'Remedies': '救濟',
  'Third-Party Rights': '第三人權利',
  'Constitutional Protections': '憲法保障',
  'General Principles': '一般原則',
  'Homicide': '殺人犯罪',
  'Inchoate Crimes': '未完成犯罪',
  'Inchoate Crimes and Parties': '未完成犯罪與共犯',
  'Criminal Trial': '刑事審判',
  'Other Crimes': '其他犯罪',
  'Hearsay': '傳聞證據',
  'Presentation of Evidence': '證據提出',
  'Privileges and Policy': '特權與政策性排除',
  'Privileges and Policy Exclusions': '特權與政策性排除',
  'Relevancy': '相關性',
  'Writings, Recordings, and Photographs': '文書、錄音與照片',
  'Mortgages and Finance': '抵押與融資',
  'Mortgages/Security Devices': '抵押與擔保物權',
  'Ownership of Real Property': '不動產所有權',
  'Real Estate Contracts': '不動產契約',
  'Rights in Real Property': '不動產權利',
  'Titles': '產權',
  'Intentional Torts': '故意侵權',
  'Negligence': '過失',
  'Other Torts': '其他侵權',
  'Products Liability': '產品責任',
  'Strict Liability': '嚴格責任',
  'Strict Liability and Products Liability': '嚴格責任與產品責任',
};

const simplifiedLabels: Record<string, string> = {
  'Civil Procedure': '民事诉讼法',
  'Constitutional Law': '宪法',
  'Contracts': '合同法',
  'Criminal Law and Procedure': '刑法与刑事诉讼法',
  'Criminal Law & Procedure': '刑法与刑事诉讼法',
  'Evidence': '证据法',
  'Real Property': '不动产法',
  'Torts': '侵权行为法',
  'Appealability and Review': '可上诉性与审查',
  'Jurisdiction and Venue': '管辖权与审判地',
  'Jury Trials': '陪审团审判',
  'Law Applied by Federal Courts': '联邦法院适用之法律',
  'Motions': '动议',
  'Pretrial Procedures': '审前程序',
  'Verdicts and Judgments': '裁决与判决',
  'Federal-State Relations': '联邦与州关系',
  'Individual Rights': '个人权利',
  'Judicial Review': '司法审查',
  'Separation of Powers': '权力分立',
  'Contract Content and Meaning': '合同内容与解释',
  'Defenses to enforceability': '可执行性抗辩',
  'Formation of Contracts': '合同成立',
  'Performance, Breach, and Discharge': '履行、违约与义务消灭',
  'Remedies': '救济',
  'Third-Party Rights': '第三人权利',
  'Constitutional Protections': '宪法保障',
  'General Principles': '一般原则',
  'Homicide': '杀人犯罪',
  'Inchoate Crimes': '未完成犯罪',
  'Inchoate Crimes and Parties': '未完成犯罪与共犯',
  'Criminal Trial': '刑事审判',
  'Other Crimes': '其他犯罪',
  'Hearsay': '传闻证据',
  'Presentation of Evidence': '证据提出',
  'Privileges and Policy': '特权与政策性排除',
  'Privileges and Policy Exclusions': '特权与政策性排除',
  'Relevancy': '相关性',
  'Writings, Recordings, and Photographs': '文书、录音与照片',
  'Mortgages and Finance': '抵押与融资',
  'Mortgages/Security Devices': '抵押与担保物权',
  'Ownership of Real Property': '不动产所有权',
  'Real Estate Contracts': '不动产合同',
  'Rights in Real Property': '不动产权利',
  'Titles': '产权',
  'Intentional Torts': '故意侵权',
  'Negligence': '过失',
  'Other Torts': '其他侵权',
  'Products Liability': '产品责任',
  'Strict Liability': '严格责任',
  'Strict Liability and Products Liability': '严格责任与产品责任',
};

export function getMbeChineseLabel(label: string, language: InterfaceLanguage): string | undefined {
  if (language === 'zh-Hans') return simplifiedLabels[label];
  if (language === 'zh-Hant') return traditionalLabels[label];
  return undefined;
}
