"use client";

import { api } from './api';

export type TodoStatus = 'new' | 'scheduled' | 'in_progress' | 'completed';
export type TodoType = 'manual' | 'review' | 'practice';

export type Todo = {
  id: string;
  user_id: string;
  title: string;
  status: TodoStatus;
  type: TodoType;
  due_date: string | null;
  chapter_id: string | null;
  chapter_ids: string | null;
  auto_generated: boolean;
  created_at: string;
  updated_at: string;
};

export type CreateTodoInput = {
  title: string;
  status?: TodoStatus;
  type?: TodoType;
  due_date?: string | null;
  chapter_id?: string | null;
  chapter_ids?: string | null;
  auto_generated?: boolean;
};

type TodoResponse = {
  id: string;
  userId: string;
  title: string;
  status: TodoStatus;
  type: TodoType;
  dueDate: string | null;
  chapterId: string | null;
  chapterIds: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
};

function toTodo(r: TodoResponse): Todo {
  return {
    id: r.id,
    user_id: r.userId,
    title: r.title,
    status: r.status,
    type: r.type,
    due_date: r.dueDate,
    chapter_id: r.chapterId,
    chapter_ids: r.chapterIds,
    auto_generated: r.autoGenerated,
    created_at: r.createdAt,
    updated_at: r.updatedAt,
  };
}

export async function fetchTodos(_userId: string): Promise<Todo[]> {
  try {
    const rows = await api.get<TodoResponse[]>('/todos');
    return rows.map(toTodo);
  } catch {
    return [];
  }
}

export async function createTodo(_userId: string, input: CreateTodoInput): Promise<Todo | null> {
  try {
    const created = await api.post<TodoResponse>('/todos', {
      title: input.title,
      status: input.status,
      type: input.type,
      dueDate: input.due_date,
      chapterId: input.chapter_id,
      chapterIds: input.chapter_ids,
      autoGenerated: input.auto_generated,
    });
    return toTodo(created);
  } catch {
    return null;
  }
}

export async function updateTodo(id: string, patch: Partial<Pick<Todo, 'title' | 'status' | 'type' | 'due_date' | 'chapter_id' | 'chapter_ids'>>): Promise<boolean> {
  try {
    await api.patch(`/todos/${id}`, {
      title: patch.title,
      status: patch.status,
      type: patch.type,
      dueDate: patch.due_date,
      chapterId: patch.chapter_id,
      chapterIds: patch.chapter_ids,
    });
    return true;
  } catch {
    return false;
  }
}

export async function deleteTodo(id: string): Promise<boolean> {
  try {
    await api.delete(`/todos/${id}`);
    return true;
  } catch {
    return false;
  }
}

/**
 * Sync auto todos from today's mission. The backend recomputes the mission via
 * the planner internally, so this just triggers the sync and returns the fresh list.
 */
export async function syncAutoTodos(_userId: string): Promise<Todo[]> {
  try {
    const rows = await api.post<TodoResponse[]>('/todos/sync-auto');
    return rows.map(toTodo);
  } catch {
    return [];
  }
}

/** Manually add a single chapter as a todo. Returns null if already exists. */
export async function addChapterAsTodo(
  _userId: string,
  chapter: { id: string; name: string; subject: string; type: 'practice' | 'review'; chapterIds?: string },
): Promise<Todo | null> {
  try {
    const created = await api.post<TodoResponse | null>('/todos/add-chapter', chapter);
    return created ? toTodo(created) : null;
  } catch (err) {
    console.error('Insert error:', err);
    return null;
  }
}
